/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sessions/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List models known to this runtime, including unavailable ones for diagnostics. */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-secret provider auth status for the runtime. */
        get: operations["listAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers/{provider}/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Store an API key for a provider in Pi auth storage. */
        put: operations["setProviderApiKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a stored provider credential from Pi auth storage. */
        delete: operations["removeProviderCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers/{provider}/subscription/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a Pi subscription OAuth login flow. */
        post: operations["startProviderSubscriptionLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/subscription/{flowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return subscription login flow state. */
        get: operations["getProviderSubscriptionLogin"];
        put?: never;
        post?: never;
        /** Cancel a pending subscription login flow. */
        delete: operations["cancelProviderSubscriptionLogin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/subscription/{flowId}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue a subscription login flow with prompt input or pasted redirect URL. */
        post: operations["continueProviderSubscriptionLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/custom/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List custom models.json providers without secret values. */
        get: operations["listCustomProviders"];
        /** Create or update a custom Pi provider in models.json. */
        put: operations["upsertCustomProvider"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/custom/providers/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a custom Pi provider from models.json. */
        delete: operations["removeCustomProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + diagnostic counters. */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered projects, newest first. */
        get: operations["listProjects"];
        put?: never;
        /** Create a project, or return the existing one (idempotent on name). */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single project's metadata. */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Remove a project: evict runtime, drop metadata, delete working dir + transcripts. */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions (persisted + in-memory not yet flushed). */
        get: operations["listSessions"];
        put?: never;
        /** Create a new session. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the active model/thinking settings for a session. */
        get: operations["getSessionSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Switch model and/or thinking level while a session is idle. */
        patch: operations["updateSessionSettings"];
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Persisted message history for a session. */
        get: operations["getSessionMessages"];
        put?: never;
        post?: never;
        /** Permanently delete a session and its persisted history. */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/extension-ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending extension UI requests for a session. */
        get: operations["listExtensionUiRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/extension-ui/{requestId}/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a pending extension UI request. */
        post: operations["respondExtensionUiRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a user prompt. Events flow over the SSE stream. */
        post: operations["sendPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort the in-flight run on a session. No-op if idle. */
        post: operations["abortSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sessions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of pi AgentSessionEvents for the session.
         * @description Long-lived `text/event-stream`. Each `data:` line carries one JSON `AgentSessionEvent` (see the `AgentSessionEvent` schema). Non-JSON lines occur too: an initial `connected to <id>` line and periodic `heartbeat` keepalive events, both of which consumers ignore. The event payload is validated against this contract server-side before being forwarded.
         */
        get: operations["streamSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Thinking/reasoning level for models that support it.
         *     Note: "xhigh" is only supported by selected model families. Use model thinking-level metadata
         *     from
         */
        ThinkingLevel: "off" | "minimal" | "low" | "medium" | "high" | "xhigh";
        AgentModelRow: {
            provider: string;
            id: string;
            name: string;
            api: string;
            reasoning: boolean;
            available: boolean;
            input: ("text" | "image")[];
            contextWindow: number;
            maxTokens: number;
            defaultThinkingLevel?: components["schemas"]["ThinkingLevel"];
        };
        ListModelsResponse: {
            models: components["schemas"]["AgentModelRow"][];
        };
        AuthProviderRow: {
            provider: string;
            name: string;
            configured: boolean;
            /** @enum {string} */
            credentialType?: "api_key" | "oauth";
            /** @enum {string} */
            source?: "stored" | "runtime" | "environment" | "fallback" | "models_json_key" | "models_json_command";
            label?: string;
            supportsApiKey: boolean;
            supportsSubscription: boolean;
            modelCount: number;
            availableModelCount: number;
        };
        ListAuthProvidersResponse: {
            providers: components["schemas"]["AuthProviderRow"][];
        };
        OkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        ErrorResponse: {
            error: string;
        };
        SetProviderApiKeyRequest: {
            key: string;
        };
        OAuthFlowState: {
            id: string;
            provider: string;
            providerName: string;
            /** @enum {string} */
            status: "starting" | "prompt" | "auth" | "waiting" | "complete" | "error" | "cancelled";
            authUrl?: string;
            instructions?: string;
            prompt?: {
                message: string;
                placeholder?: string;
                allowEmpty?: boolean;
            };
            progress: string[];
            error?: string;
            expiresAt: string;
        };
        ContinueOAuthFlowRequest: {
            value: string;
        };
        CustomProviderModel: {
            id: string;
            name?: string;
            /** @enum {string} */
            api?: "openai-completions" | "openai-responses" | "anthropic-messages";
            reasoning?: boolean;
            thinkingLevelMap?: {
                [key: string]: string | null;
            };
            input?: ("text" | "image")[];
            contextWindow?: number;
            maxTokens?: number;
            compat?: {
                [key: string]: unknown;
            };
        };
        CustomProviderRow: {
            provider: string;
            name?: string;
            baseUrl?: string;
            /** @enum {string} */
            api?: "openai-completions" | "openai-responses" | "anthropic-messages";
            apiKeyConfigured: boolean;
            modelCount: number;
            models: components["schemas"]["CustomProviderModel"][];
        };
        ListCustomProvidersResponse: {
            providers: components["schemas"]["CustomProviderRow"][];
        };
        UpsertCustomProviderRequest: {
            provider: string;
            name?: string;
            /** Format: uri */
            baseUrl: string;
            /** @enum {string} */
            api: "openai-completions" | "openai-responses" | "anthropic-messages";
            apiKey?: string;
            models: components["schemas"]["CustomProviderModel"][];
        };
        HealthResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @enum {string} */
            service: "agent-server";
            time: string;
            /** @description Map of SSE channel name → current subscriber count. */
            channels: {
                [key: string]: number;
            };
        };
        ProjectInfo: {
            /**
             * @description Immutable slug; registry key, route param, and directory name.
             * @example my-cool-app
             */
            id: string;
            /** @example My Cool App */
            name: string;
            /**
             * @description Absolute working directory under WORKSPACE_DIR.
             * @example /workspace/my-cool-app
             */
            projectDir: string;
            /**
             * @description ISO-8601 UTC timestamp
             * @example 2026-06-03T10:00:00.000Z
             */
            createdAt: string;
        };
        CreateProjectRequest: {
            /**
             * @description Human-facing project name. Slugified into the immutable id and directory name.
             * @example My Cool App
             */
            name: string;
        };
        ListProjectsResponse: {
            projects: components["schemas"]["ProjectInfo"][];
        };
        SessionRow: {
            /** @example 01J9Z... */
            id: string;
            /**
             * @description ISO-8601 UTC timestamp
             * @example 2026-05-17T10:00:00.000Z
             */
            createdAt: string;
            /** @description First user message; empty for never-prompted sessions. */
            firstMessage: string;
            messageCount: number;
        };
        ListSessionsResponse: {
            sessions: components["schemas"]["SessionRow"][];
        };
        CreateSessionResponse: {
            id: string;
            createdAt: string;
        };
        SessionModelSettingsResponse: {
            model: components["schemas"]["AgentModelRow"] | null;
            thinkingLevel: components["schemas"]["ThinkingLevel"];
            availableThinkingLevels: components["schemas"]["ThinkingLevel"][];
            supportsThinking: boolean;
            isStreaming: boolean;
        };
        PatchSessionSettingsRequest: {
            provider?: string;
            modelId?: string;
            thinkingLevel?: components["schemas"]["ThinkingLevel"];
        };
        SessionMessagesResponse: {
            id: string;
            /** @description Pi-shaped message objects. Forwarded as-is at runtime; published as AgentMessage[] in the contract. */
            messages: components["schemas"]["AgentMessage"][];
        };
        PendingExtensionUiRequestsResponse: {
            /** @description Pending extension UI request events. Forwarded as-is at runtime; published as ExtensionUiRequest[] in the contract. */
            requests: components["schemas"]["ExtensionUiRequest"][];
        };
        ExtensionUiResponseRequest: {
            value: string;
        } | {
            confirmed: boolean;
        } | {
            /** @enum {boolean} */
            cancelled: true;
        };
        PromptRequest: {
            /** @example find me events this weekend */
            text: string;
        };
        /** @description Every JSON event agent-server forwards on `GET …/sessions/{id}/events`. */
        WireEvent: {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "select";
            title: string;
            options: string[];
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "confirm";
            title: string;
            message: string;
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "input";
            title: string;
            placeholder?: string;
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "editor";
            title: string;
            prefill?: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "notify";
            message: string;
            notifyType?: "info" | "warning" | "error";
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setStatus";
            statusKey: string;
            statusText?: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setWidget";
            widgetKey: string;
            widgetLines?: string[];
            widgetPlacement?: "aboveEditor" | "belowEditor";
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setTitle";
            title: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "set_editor_text";
            text: string;
        } | components["schemas"]["ExtensionErrorEvent"] | {
            /** @constant */
            type: "agent_start";
        } | {
            /** @constant */
            type: "turn_start";
        } | {
            /** @constant */
            type: "turn_end";
            message: components["schemas"]["AgentMessage"];
            toolResults: components["schemas"]["ToolResultMessageany_o1"][];
        } | {
            /** @constant */
            type: "message_start";
            message: components["schemas"]["AgentMessage"];
        } | {
            /** @constant */
            type: "message_update";
            message: components["schemas"]["AgentMessage"];
            assistantMessageEvent: components["schemas"]["AssistantMessageEvent"];
        } | {
            /** @constant */
            type: "message_end";
            message: components["schemas"]["AgentMessage"];
        } | {
            /** @constant */
            type: "tool_execution_start";
            toolCallId: string;
            toolName: string;
            args: unknown;
        } | {
            /** @constant */
            type: "tool_execution_update";
            toolCallId: string;
            toolName: string;
            args: unknown;
            partialResult: unknown;
        } | {
            /** @constant */
            type: "tool_execution_end";
            toolCallId: string;
            toolName: string;
            result: unknown;
            isError: boolean;
        } | {
            /** @constant */
            type: "agent_end";
            messages: components["schemas"]["AgentMessage"][];
            willRetry: boolean;
        } | {
            /** @constant */
            type: "queue_update";
            steering: string[];
            followUp: string[];
        } | {
            /** @constant */
            type: "compaction_start";
            reason: "manual" | "threshold" | "overflow";
        } | {
            /** @constant */
            type: "session_info_changed";
            name?: string;
        } | {
            /** @constant */
            type: "thinking_level_changed";
            level: components["schemas"]["ThinkingLevel"];
        } | {
            /** @constant */
            type: "compaction_end";
            reason: "manual" | "threshold" | "overflow";
            result?: components["schemas"]["CompactionResultunknown"];
            aborted: boolean;
            willRetry: boolean;
            errorMessage?: string;
        } | {
            /** @constant */
            type: "auto_retry_start";
            attempt: number;
            maxAttempts: number;
            delayMs: number;
            errorMessage: string;
        } | {
            /** @constant */
            type: "auto_retry_end";
            success: boolean;
            attempt: number;
            finalError?: string;
        };
        /** @description Emitted when a pi extension handler throws; surfaced to the UI for visibility. */
        ExtensionErrorEvent: {
            /** @constant */
            type: "extension_error";
            extensionPath: string;
            /** @description The pi lifecycle event during which the error occurred (e.g. "session_start"). */
            event?: string;
            error: string;
            stack?: string;
        };
        /**
         * @description AgentMessage: Union of LLM messages + custom messages.
         *     This abstraction allows apps to add custom message types while maintaining
         *     type safety and compatibility with the base LLM messages.
         */
        AgentMessage: components["schemas"]["UserMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["ToolResultMessageany"] | components["schemas"]["BashExecutionMessage"] | components["schemas"]["CustomMessageunknown"] | components["schemas"]["BranchSummaryMessage"] | components["schemas"]["CompactionSummaryMessage"];
        UserMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            content: string | (components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])[];
            timestamp: number;
        };
        TextContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            text: string;
            textSignature?: string;
        };
        ImageContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            data: string;
            mimeType: string;
        };
        AssistantMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            content: (components["schemas"]["TextContent"] | components["schemas"]["ThinkingContent"] | components["schemas"]["ToolCall"])[];
            api: components["schemas"]["Api"];
            provider: string;
            model: string;
            responseModel?: string;
            responseId?: string;
            diagnostics?: components["schemas"]["AssistantMessageDiagnostic"][];
            usage: components["schemas"]["Usage"];
            stopReason: components["schemas"]["StopReason"];
            errorMessage?: string;
            timestamp: number;
        };
        ThinkingContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "thinking";
            thinking: string;
            thinkingSignature?: string;
            /**
             * @description When true, the thinking content was redacted by safety filters. The opaque
             *     encrypted payload is stored in `thinkingSignature` so it can be passed back
             *     to the API for multi-turn continuity.
             */
            redacted?: boolean;
        };
        ToolCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "toolCall";
            id: string;
            name: string;
            arguments: components["schemas"]["Recordstringany"];
            thoughtSignature?: string;
        };
        /** @description Construct a type with a set of properties K of type T */
        Recordstringany: {
            [key: string]: unknown;
        };
        Api: string;
        AssistantMessageDiagnostic: {
            type: string;
            timestamp: number;
            error?: components["schemas"]["DiagnosticErrorInfo"];
            details?: components["schemas"]["Recordstringunknown"];
        };
        DiagnosticErrorInfo: {
            name?: string;
            message: string;
            stack?: string;
            code?: string | number;
        };
        /** @description Construct a type with a set of properties K of type T */
        Recordstringunknown: {
            [key: string]: unknown;
        };
        Usage: {
            input: number;
            output: number;
            cacheRead: number;
            cacheWrite: number;
            totalTokens: number;
            cost: {
                input: number;
                output: number;
                cacheRead: number;
                cacheWrite: number;
                total: number;
            };
        };
        StopReason: "error" | "stop" | "length" | "toolUse" | "aborted";
        ToolResultMessageany: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "toolResult";
            toolCallId: string;
            toolName: string;
            content: (components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])[];
            details?: unknown;
            isError: boolean;
            timestamp: number;
        };
        BashExecutionMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "bashExecution";
            command: string;
            output: string;
            exitCode?: number;
            cancelled: boolean;
            truncated: boolean;
            fullOutputPath?: string;
            timestamp: number;
            excludeFromContext?: boolean;
        };
        CustomMessageunknown: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "custom";
            customType: string;
            content: string | (components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])[];
            display: boolean;
            details?: unknown;
            timestamp: number;
        };
        BranchSummaryMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "branchSummary";
            summary: string;
            fromId: string;
            timestamp: number;
        };
        CompactionSummaryMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "compactionSummary";
            summary: string;
            tokensBefore: number;
            timestamp: number;
        };
        ToolResultMessageany_o1: {
            /** @constant */
            role: "toolResult";
            toolCallId: string;
            toolName: string;
            content: (components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])[];
            details?: unknown;
            isError: boolean;
            timestamp: number;
        };
        /**
         * @description Event protocol for AssistantMessageEventStream.
         *
         *     Streams should emit `start` before partial updates, then terminate with either:
         *     - `done` carrying the final successful AssistantMessage, or
         *     - `error` carrying the final AssistantMessage with stopReason "error" or "aborted"
         *       and errorMessage.
         */
        AssistantMessageEvent: {
            /** @constant */
            type: "start";
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "text_start";
            contentIndex: number;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "text_delta";
            contentIndex: number;
            delta: string;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "text_end";
            contentIndex: number;
            content: string;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "thinking_start";
            contentIndex: number;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "thinking_delta";
            contentIndex: number;
            delta: string;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "thinking_end";
            contentIndex: number;
            content: string;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "toolcall_start";
            contentIndex: number;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "toolcall_delta";
            contentIndex: number;
            delta: string;
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "toolcall_end";
            contentIndex: number;
            toolCall: components["schemas"]["ToolCall"];
            partial: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "done";
            reason: "stop" | "length" | "toolUse";
            message: components["schemas"]["AssistantMessage"];
        } | {
            /** @constant */
            type: "error";
            reason: "error" | "aborted";
            error: components["schemas"]["AssistantMessage"];
        };
        /** @description Result from compact() - SessionManager adds uuid/parentUuid when saving */
        CompactionResultunknown: {
            summary: string;
            firstKeptEntryId: string;
            tokensBefore: number;
            /** @description Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
            details?: unknown;
        };
        ExtensionUiRequest: {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "select";
            title: string;
            options: string[];
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "confirm";
            title: string;
            message: string;
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "input";
            title: string;
            placeholder?: string;
            timeout?: number;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "editor";
            title: string;
            prefill?: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "notify";
            message: string;
            notifyType?: "info" | "warning" | "error";
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setStatus";
            statusKey: string;
            statusText?: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setWidget";
            widgetKey: string;
            widgetLines?: string[];
            widgetPlacement?: "aboveEditor" | "belowEditor";
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "setTitle";
            title: string;
        } | {
            /** @constant */
            type: "extension_ui_request";
            id: string;
            /** @constant */
            method: "set_editor_text";
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListModelsResponse"];
                };
            };
        };
    };
    listAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known providers and whether each has configured auth. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAuthProvidersResponse"];
                };
            };
        };
    };
    setProviderApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProviderApiKeyRequest"];
            };
        };
        responses: {
            /** @description Credential stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Invalid provider or key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeProviderCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential removed if it existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Invalid provider. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startProviderSubscriptionLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current flow state. Continue if a prompt or pasted redirect is required. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthFlowState"];
                };
            };
            /** @description Provider does not support subscription auth. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProviderSubscriptionLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current flow state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthFlowState"];
                };
            };
            /** @description Flow not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelProviderSubscriptionLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled flow state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthFlowState"];
                };
            };
            /** @description Flow not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    continueProviderSubscriptionLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueOAuthFlowRequest"];
            };
        };
        responses: {
            /** @description Updated flow state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthFlowState"];
                };
            };
            /** @description Invalid input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Flow not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCustomProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom providers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCustomProvidersResponse"];
                };
            };
        };
    };
    upsertCustomProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCustomProviderRequest"];
            };
        };
        responses: {
            /** @description Custom provider saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomProviderRow"];
                };
            };
            /** @description Invalid custom provider config. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeCustomProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom provider removed if it existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Invalid provider. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description The created or already-existing project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"];
                };
            };
            /** @description Name does not yield a valid project id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"];
                };
            };
            /** @description Unknown project id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project removed if it existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unknown project id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionsResponse"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newly created session metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
        };
    };
    getSessionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session model settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionModelSettingsResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSessionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSessionSettingsRequest"];
            };
        };
        responses: {
            /** @description Effective session model settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionModelSettingsResponse"];
                };
            };
            /** @description Invalid settings body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown session id or model id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Session is currently running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected settings update error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages for the session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMessagesResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listExtensionUiRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending extension UI request events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingExtensionUiRequestsResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    respondExtensionUiRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtensionUiResponseRequest"];
            };
        };
        responses: {
            /** @description Extension UI response accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unknown session id or request id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequest"];
            };
        };
        responses: {
            /** @description Prompt accepted and queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    abortSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abort accepted (or no-op if session was idle). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. Each `data:` line is a JSON-encoded AgentSessionEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["WireEvent"];
                };
            };
            /** @description Unknown session id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
